# Generated by Selenium IDE
import allure
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from allure_commons._allure import attach
from allure_commons.types import AttachmentType

class TestSearch():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless")
    service = Service('/home/zheying/chromedriver')
    self.driver = webdriver.Chrome(options=options, service=service)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(1296, 768)
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("Core consulting")
    self.driver.find_element(By.NAME, "btnK").click()
    time.sleep(5)
    allure.attach(self.driver.get_screenshot_as_png(), name="Google_Search_SS", attachment_type=allure.attachment_type.PNG)
  
